FROM alpine:latest

COPY docker-image-files /

RUN \
  chmod +x /test.sh && \
  apk --update add bash iperf gcc musl-dev && \
  gcc membomb.c -o /membomb && \
  apk del gcc musl-dev&& \
  rm -rf /var/cache/apk/*

EXPOSE 5001
#CMD ["help"]
ENTRYPOINT ["/test2.sh"]
